/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const CreatePostRequest = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'featuredImageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const PostId = IDL.Nat;
export const BlogPost = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'featuredImageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const InquiryId = IDL.Nat;
export const ContactInquiry = IDL.Record({
  'id' : InquiryId,
  'serviceInterested' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const CreateInquiryRequest = IDL.Record({
  'serviceInterested' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdatePostRequest = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Timestamp,
  'author' : IDL.Text,
  'readTime' : IDL.Nat,
  'featuredImageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'createBlogPost' : IDL.Func([CreatePostRequest], [BlogPost], []),
  'deleteBlogPost' : IDL.Func([PostId], [IDL.Bool], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getBlogPostById' : IDL.Func([PostId], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'submitContactInquiry' : IDL.Func(
      [CreateInquiryRequest],
      [ContactInquiry],
      [],
    ),
  'updateBlogPost' : IDL.Func([UpdatePostRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const CreatePostRequest = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'featuredImageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const PostId = IDL.Nat;
  const BlogPost = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'featuredImageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const InquiryId = IDL.Nat;
  const ContactInquiry = IDL.Record({
    'id' : InquiryId,
    'serviceInterested' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const CreateInquiryRequest = IDL.Record({
    'serviceInterested' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdatePostRequest = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Timestamp,
    'author' : IDL.Text,
    'readTime' : IDL.Nat,
    'featuredImageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'createBlogPost' : IDL.Func([CreatePostRequest], [BlogPost], []),
    'deleteBlogPost' : IDL.Func([PostId], [IDL.Bool], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getBlogPostById' : IDL.Func([PostId], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'submitContactInquiry' : IDL.Func(
        [CreateInquiryRequest],
        [ContactInquiry],
        [],
      ),
    'updateBlogPost' : IDL.Func([UpdatePostRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };