/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : PostId,
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'author' : string,
  'readTime' : bigint,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactInquiry {
  'id' : InquiryId,
  'serviceInterested' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export interface CreateInquiryRequest {
  'serviceInterested' : string,
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'phone' : string,
}
export interface CreatePostRequest {
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'author' : string,
  'readTime' : bigint,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export type InquiryId = bigint;
export type PostId = bigint;
export type Timestamp = bigint;
export interface UpdatePostRequest {
  'id' : PostId,
  'title' : string,
  'content' : string,
  'publishDate' : Timestamp,
  'author' : string,
  'readTime' : bigint,
  'featuredImageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface _SERVICE {
  'createBlogPost' : ActorMethod<[CreatePostRequest], BlogPost>,
  'deleteBlogPost' : ActorMethod<[PostId], boolean>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getBlogPostById' : ActorMethod<[PostId], [] | [BlogPost]>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'submitContactInquiry' : ActorMethod<[CreateInquiryRequest], ContactInquiry>,
  'updateBlogPost' : ActorMethod<[UpdatePostRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];